export type FreeGamesPromotions = {
  error: unknown[]
  data: {
    Catalog: {
      searchStore: {
        elements: Element[]
        paging: {
          count: number
          total: number
        }
      }
    }
  }
}

export type Element<T = string> = {
  title: string
  id: string
  namespace: string
  description: string
  effectiveDate: T // Date
  offerType: string | 'BASE_GAME' | 'ADD_ON' | 'BUNDLE' | 'OTHERS'
  expiryDate: null
  viewableDate: T // | Date
  status: string | 'ACTIVE'
  isCodeRedemptionOnly: boolean
  keyImages: KeyImage[]
  seller: {
    id: string
    name: string | 'Epic Dev Test Account'
  }
  productSlug: string | null
  urlSlug: string
  url: null
  items: { id: string; namespace: string }[]
  customAttributes: CustomAttributes[]
  categories: Categories[]
  tags: { id: string }[] | []
  catalogNs: {
    mappings:
      | null
      | []
      | {
          pageSlug: string
          pageType: string | 'productHome'
        }[]
  }
  offerMappings:
    | null
    | []
    | {
        pageSlug: string
        pageType: string | 'offer' | 'productHome'
      }[]
  price: {
    totalPrice: {
      discountPrice: number
      originalPrice: number
      voucherDiscount: number
      discount: number
      currencyCode: string | 'EUR'
      currencyInfo: { decimals: number }
      fmtPrice: {
        originalPrice: string
        discountPrice: string
        intermediatePrice: string
      }
    }
    lineOffers: { appliedRules: [] | LineOffersAppliedRules<T>[] }[]
  }
  promotions: null | {
    promotionalOffers: /****** */
    [] | { promotionalOffers: PromotionalOffers<T>[] }[]
    upcomingPromotionalOffers?:
      | []
      | { promotionalOffers: PromotionalOffers<T>[] }[]
  }
}

export type KeyImage = {
  type:
    | 'OfferImageWide'
    | 'OfferImageTall'
    | 'Thumbnail'
    | 'featuredMedia'
    | 'DieselStoreFrontWide'
    | 'VaultClosed'
    | string
  url: string
}

type CustomAttributes =
  | {
      key:
        | string
        | 'isManuallySetRefundableType'
        | 'autoGeneratedPrice'
        | 'isManuallySetViewableDate'
        | 'isPromotionalContentUsed'
        | 'isManuallySetPCReleaseDate'
        | 'isBlockchainUsed'
      value: string | 'false' | 'true' | 'null' | '[]'
    }
  | {
      key: 'com.epicgames.app.freegames.vault.close'
      value: '[]'
    }
  | {
      key: 'com.epicgames.app.blacklist'
      value: '[]'
    }
  | {
      key: 'com.epicgames.app.freegames.vault.slug'
      value: string | 'free-games'
    }
  | {
      key: 'com.epicgames.app.freegames.vault.open'
      value: '[]'
    }

type Categories = {
  path:
    | string
    | 'addons'
    | 'addons/durable'
    | 'applications'
    | 'bundles'
    | 'bundles/games'
    | 'freegames'
    | 'freegames/vaulted'
    | 'games'
    | 'games/edition'
    | 'games/edition/base'
}

type LineOffersAppliedRules<T = string> = {
  id: string
  endDate: T // Date
  discountSetting: { discountType: string | 'PERCENTAGE' }
}

type PromotionalOffers<D = string> = {
  startDate: D // Date
  endDate: D // Date
  discountSetting: {
    discountType: string | 'PERCENTAGE'
    discountPercentage: number
  }
}
